// <auto-generated />
using Final_Project_Hobbies.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Project_Hobbies.Migrations
{
    [DbContext(typeof(HobbyContext))]
    partial class HobbyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Final_Project_Hobbies.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = "Battle Royale",
                            Title = "Apex Legends"
                        },
                        new
                        {
                            Id = 2,
                            Genre = "Strategy",
                            Title = "Bloons TD"
                        },
                        new
                        {
                            Id = 3,
                            Genre = "Action-RPG",
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 4,
                            Genre = "Metroidvania",
                            Title = "Hollow Knight"
                        },
                        new
                        {
                            Id = 5,
                            Genre = "Metroidvania",
                            Title = "Hollow Knight: Silksong"
                        },
                        new
                        {
                            Id = 6,
                            Genre = "Sandbox",
                            Title = "Minecraft"
                        },
                        new
                        {
                            Id = 7,
                            Genre = "Open World",
                            Title = "Subnautica"
                        },
                        new
                        {
                            Id = 8,
                            Genre = "Open World",
                            Title = "Subnautica: Below Zero"
                        },
                        new
                        {
                            Id = 9,
                            Genre = "Platformer",
                            Title = "Super Mario Galaxy"
                        },
                        new
                        {
                            Id = 10,
                            Genre = "Platformer",
                            Title = "Super Mario Galaxy 2"
                        },
                        new
                        {
                            Id = 11,
                            Genre = "Platformer",
                            Title = "Super Paper Mario"
                        },
                        new
                        {
                            Id = 12,
                            Genre = "Action",
                            Title = "Sekiro"
                        },
                        new
                        {
                            Id = 13,
                            Genre = "Simulation",
                            Title = "Stardew Valley"
                        },
                        new
                        {
                            Id = 14,
                            Genre = "Sandbox",
                            Title = "Terraria"
                        },
                        new
                        {
                            Id = 15,
                            Genre = "Action-Adventure",
                            Title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 16,
                            Genre = "Action-Adventure",
                            Title = "The Legend of Zelda: Skyward Sword"
                        },
                        new
                        {
                            Id = 17,
                            Genre = "Action-Adventure",
                            Title = "The Legend of Zelda: Windwaker"
                        },
                        new
                        {
                            Id = 18,
                            Genre = "Simulation",
                            Title = "PowerWash Simulator"
                        },
                        new
                        {
                            Id = 19,
                            Genre = "Sports",
                            Title = "PGA Tour"
                        },
                        new
                        {
                            Id = 20,
                            Genre = "RPG",
                            Title = "Pokemon"
                        },
                        new
                        {
                            Id = 21,
                            Genre = "First-Person Shooter",
                            Title = "Halo"
                        },
                        new
                        {
                            Id = 22,
                            Genre = "First-Person Shooter",
                            Title = "Call of Duty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
